export const AssignmentServiceContent = [
    {
        title: "Assignment Service",
        briefDescription: "The ever-growing pile of assignments is the worst nightmare a student can have. Teachers and professors are brutal in this department. Meritmates understand this problem well. The anxiety of incomplete assignments is the main source of stress building. We want you to help you, as taking a huge amount of unnecessary stress will be a devastating problem considering your age. So you can leave your incomplete assignment in the custody of our highly-qualified writers. They'll complete your assignment as soon as you want. Long gone were the days of stressful assignment!. We will complete your assignment following your university strict guidelines and the needed referencing style. Meritmates can help you in short- and long-term assignments. Our writers are highly efficient in working on tight deadlines too. So, we can save you no matter the odds.",
        img: "./assets/samples_doc-b47c8242c7628fbf81a699747abe17fed61711df2980a2f77a5d8df5efb03a86.jpg",
        heading: "Features of the Assignment Service",
        amount: "£7.34",
        options: [
            {
                value:"100% Original Product"
            },
            {
                value:"Complete Money Back Guarantees"
            },
            {
                value:"Privacy and Security"
            },
            {
                value:"24/7 Help and Assistance"
            }
        ],
        titleMedium: "Short-term assignment",
        firstdescription: ["Short-term assignments include every assignment that can be completed within a day or two. Short term assignment usually includes:",
                            "Short essays",
                            "Writing short stories",
                            "Literary critique",
                            "Article summaries",
                            "Answers related to a text",
                            "Calculation of a math problem",
                            "Hard physics numerical",
                            "An annotated bibliography is a list of resources, includes books, articles, or documents.",
                            "Reports generally involve presenting your investigation and analysis of information or an issue, recommending actions and making proposals",
                            "A case study is an in-depth investigation conducted to collect and present detailed information about anything.",
                            "An abstract is a summary of any article, thesis, conference presentation, or in-depth research.",
                            "Any critical review or literary review.",
                            "If you did not find what you are looking for you can directly contact us."],
        help: "Long-term assignment",
        helpdescription : ["Long-term assignment as the term suggests is an assignment that takes a longer period to complete. Time management is a key factor in completing a long-term assignment. We guarantee you that we will take your work and complete it before the deadline. Some of the Long-term assignment we provide:",
                            "Abstract",
                            "Advertisement",
                            "Annotated bibliography",
                            "Biography or autobiography",
                            "multimedia or slide presentation",
                            "Multiple-choice test",
                            "Plan for conducting a project",
                            "A poem, play, choreography",
                            "Review of the book, play, exhibit",
                            "Review of literature",
                            "Term paper, research paper",
                            "Thesis sentence (the sentence that expresses the author's main point)",
                            "Academic Proposals.",
                            "It is not possible to include every topic here so if your desired paper is not included? Just contact us we will assist you."],
        titleConnect : "Our Process",
        connectDescription: ["The main reason, a student needs writing service is to complete their work before the deadlines while maintaining the quality.",
                            "So as soon as your orders are placed, a unique customer ID will be generated. You can comfortably communicate with your assigned personal manager for further details. We will provide you the writer who is specialized in that particular area according to your information in the form. The writer will immediately contact you via personal manager so that he can start working immediately on your assignment.",
                            "We will make sure that contact between you and our experts will be highly confidential and 100% safe.",
                            "The client can check their progress. You also have full rights to evaluate your work once it is completed.",
                            "Don't worry about the quality because your assignment will pass through a very heavy rechecking and proofreading process. We use 'Turnitin' for plagiarism reports. We will provide you with the first draft once it is completed. You can show it to your tutor and provide us with his/her feedback then we will re-edit your paper. Our expert editors will proofread your work and rate it out of 10. After all the amendments, we will provide you your final copy. If you want to change or edit something, we'll do it instantly for you.",
                            "We want to provide you the best result as possible. Your grades are on the line here. Your satisfaction is most necessary for us. I'm sure once you'll work with us you will return in the future for our help."],
        nextStep: "Benefits of our assignment services",
        nextDescription: ["A personal, high qualified writer and a friendly personal manager.",
                            "Guarantee of plagiarism-free content with the help of 'Turnitin' plagiarism reports.",
                            "Your work will be original and free of any annoying grammatical errors.",
                            "We will re-edit your assignment until you are happy with the final product.",
                            "The presentation of your assignment paper will be unique and speaks quality. You can see our reviews too.",
                            "All the writers are native English-speakers so it will be easier to communicate and discuss your ideas with them.",
                            "24*7 hours services, you can check your progress whenever you want, wherever you want.",
                            "The writer will research heavily to provide you one of the best results a student can have.",
                            "We guarantee your work will be completed before the deadline.",
                            "We will do your work even if you are tight in the deadline department.",
                            "The most important of all, Meritmates has very student-friendly pricing. We already did extensive research on the budget of an average UK student. So, you will be surprised by our student affordable deals.",
                            "We provide you a great deal of diverse content. This is where Meritmates shines the most.",
                            "Our writers are handpicked expert scholars from around the world. So, there is nothing out of course in our library.",
                            "We will take full responsibility for your good grades. (Sometimes personal relationship between you and your tutor may affect your grades, we can't take responsibility for your accounts.)",
                            "Your paper will be written in grammatically correct English language, with complete sentences, and relatively error-free.",
                            "We will create a comfortable communication environment so that you converse our team of experts including the personal manager, the academic writer who will finish your assignment, the researcher, and the editors."],
        writing: "",
        writingDescription: [],
        price: "Pricing",
        priceDescription: ["Meritmates' service prices are very student-friendly. We understand the tight budget of a student. We are not here for business we genuinely want to help you secure a successful future that is the reason we focus mainly on keeping our price as low as possible while providing the best quality standards."],
        conclusion: "",
        conDescription: [],
        btnText: "Order essay Now",
        titleProcess: "",
        processDescription: []
    }
]